# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: faherrau <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/02/22 15:17:40 by faherrau          #+#    #+#              #
#    Updated: 2021/02/24 08:38:50 by faherrau         ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

SRCS += ./add_vector_coord.c
SRCS += ./add_vector_vector.c
SRCS += ./color_to_int.c
SRCS += ./create_color.c
SRCS += ./create_interval.c
SRCS += ./create_point3.c
SRCS += ./create_vector.c
SRCS += ./distance2.c
SRCS += ./distance3.c
SRCS += ./distance_point3.c
SRCS += ./distance_square2.c
SRCS += ./distance_square3.c
SRCS += ./distance_square_point3.c
SRCS += ./div_vector_coord.c
SRCS += ./div_vector_value.c
SRCS += ./div_vector_vector.c
SRCS += ./ft_abs.c
SRCS += ./ft_append_strs.c
SRCS += ./ft_atoi.c
SRCS += ./ft_bzero.c
SRCS += ./ft_calloc.c
SRCS += ./ft_close_file.c
SRCS += ./ft_contains_char.c
SRCS += ./ft_count_file_lines.c
SRCS += ./ft_ctostr.c
SRCS += ./ft_fabs.c
SRCS += ./ft_find_char.c
SRCS += ./ft_fmax.c
SRCS += ./ft_fmin.c
SRCS += ./ft_iabsui.c
SRCS += ./ft_ll_length.c
SRCS += ./ft_lltoa_ibase.c
SRCS += ./ft_lowercase_char.c
SRCS += ./ft_map.c
SRCS += ./ft_max.c
SRCS += ./ft_memset.c
SRCS += ./ft_min.c
SRCS += ./ft_natoi.c
SRCS += ./ft_open_file.c
SRCS += ./ft_printf.c
SRCS += ./ft_putchar.c
SRCS += ./ft_putchar_err.c
SRCS += ./ft_putchar_errnl.c
SRCS += ./ft_putchar_fd.c
SRCS += ./ft_putchar_fdnl.c
SRCS += ./ft_putchar_nl.c
SRCS += ./ft_puti.c
SRCS += ./ft_puti_err.c
SRCS += ./ft_puti_errnl.c
SRCS += ./ft_puti_fd.c
SRCS += ./ft_puti_fdnl.c
SRCS += ./ft_puti_nl.c
SRCS += ./ft_putl.c
SRCS += ./ft_putl_err.c
SRCS += ./ft_putl_errnl.c
SRCS += ./ft_putl_fd.c
SRCS += ./ft_putl_fdnl.c
SRCS += ./ft_putl_nl.c
SRCS += ./ft_putll.c
SRCS += ./ft_putll_err.c
SRCS += ./ft_putll_errnl.c
SRCS += ./ft_putll_fd.c
SRCS += ./ft_putll_fdnl.c
SRCS += ./ft_putll_nl.c
SRCS += ./ft_putnchar.c
SRCS += ./ft_putnchar_err.c
SRCS += ./ft_putnchar_errnl.c
SRCS += ./ft_putnchar_fd.c
SRCS += ./ft_putnchar_fdnl.c
SRCS += ./ft_putnchar_nl.c
SRCS += ./ft_putstr.c
SRCS += ./ft_putstr_err.c
SRCS += ./ft_putstr_errnl.c
SRCS += ./ft_putstr_fd.c
SRCS += ./ft_putstr_fdnl.c
SRCS += ./ft_putstr_nl.c
SRCS += ./ft_putui.c
SRCS += ./ft_putui_err.c
SRCS += ./ft_putui_errnl.c
SRCS += ./ft_putui_fd.c
SRCS += ./ft_putui_fdnl.c
SRCS += ./ft_putui_nl.c
SRCS += ./ft_putul.c
SRCS += ./ft_putul_err.c
SRCS += ./ft_putul_errnl.c
SRCS += ./ft_putul_fd.c
SRCS += ./ft_putul_fdnl.c
SRCS += ./ft_putul_nl.c
SRCS += ./ft_putull.c
SRCS += ./ft_putull_err.c
SRCS += ./ft_putull_errnl.c
SRCS += ./ft_putull_fd.c
SRCS += ./ft_putull_fdnl.c
SRCS += ./ft_putull_nl.c
SRCS += ./ft_read_next_line.c
SRCS += ./ft_strcpy.c
SRCS += ./ft_strdup.c
SRCS += ./ft_strlen.c
SRCS += ./ft_strmult_back.c
SRCS += ./ft_strmult_front.c
SRCS += ./ft_strndup.c
SRCS += ./ft_tolower.c
SRCS += ./ft_toupper.c
SRCS += ./ft_ull_ibase_length.c
SRCS += ./ft_ull_length.c
SRCS += ./ft_ulltoa_ibase.c
SRCS += ./ft_uppercase_char.c
SRCS += ./is_alpha.c
SRCS += ./is_alphanumeric.c
SRCS += ./is_ascii.c
SRCS += ./is_lowercase.c
SRCS += ./is_numeric.c
SRCS += ./is_printable.c
SRCS += ./is_space.c
SRCS += ./is_uppercase.c
SRCS += ./is_whitespace.c
SRCS += ./mult_vector_coord.c
SRCS += ./mult_vector_value.c
SRCS += ./mult_vector_vector.c
SRCS += ./rotate_vector.c
SRCS += ./rotate_vector_x.c
SRCS += ./rotate_vector_y.c
SRCS += ./rotate_vector_z.c
SRCS += ./sub_vector_coord.c
SRCS += ./sub_vector_vector.c
SRCS += ./checkers.c
SRCS += ./ft_printf_displayer.c
SRCS += ./ft_printf.c
SRCS += ./main_parse_function.c
SRCS += ./main_process_function.c
SRCS += ./preprocessing.c
SRCS += ./structure_init.c
SRCS += ./subparsing_functions.c
SRCS += ./subprocessing_basictags.c
SRCS += ./subprocessing_boringtags.c

NAME		=	libftprintf.a

INCLUDES	=	./
OBJS		=	$(SRCS:.c=.o)

GCC			=	gcc
FLAGS		=	-Wall -Wextra -Werror
RM			=	rm -f

.c.o:
	$(GCC) $(FLAGS) -I $(INCLUDES) -c $< -o $(<:.c=.o)

$(NAME): $(OBJS)
	ar rc $(NAME) $(OBJS)

all: $(NAME)

clean:
	$(RM) $(OBJS)

fclean: clean
	$(RM) $(NAME)

re: fclean all

gmk:
	./scripts/generate-mk.sh

norminette: clean
	@echo " "
	norminettev2 sources
	@echo " "
	norminettev2 includes

test: $(NAME)
	@echo "----- MAKEFILE TESTS -----"
	
export:
	./scripts/export.sh

end:
	./scripts/end.sh

.PHONY: all clean fclean re gmk norminette test export end
